export const GET_ACCOUNT_LIST = 'GET_ACCOUNT_LIST';
export const GET_ACCOUNT_LIST_SUCCESS = 'GET_ACCOUNT_LIST_SUCCESS';
export const POST_CHAT = 'POST_CHAT';
export const POST_CHAT_SUCCESS = 'POST_CHAT_SUCCESS';
export const POST_CHAT_FEEDBACK = 'POST_CHAT_FEEDBACK';
export const POST_CHAT_FEEDBACK_SUCCESS = 'POST_CHAT_FEEDBACK_SUCCESS';
export const POST_CHAT_FEEDBACK_FORM = 'POST_CHAT_FEEDBACK_FORM';
export const POST_CHAT_FEEDBACK_FORM_SUCCESS =
  'POST_CHAT_FEEDBACK_FORM_SUCCESS';
export const POST_CHAT_ERROR = 'POST_CHAT_ERROR';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const GET_TRENDING_TOPICS = 'GET_TRENDING_TOPICS';
export const EMPLOYEE_TIME_OFF = 'EMPLOYEE_TIME_OFF';
export const GET_TRENDING_TOPICS_SUCCESS = 'GET_TRENDING_TOPICS_SUCCESS';
export const EMPLOYEE_TIME_OFF_SUCCESS = 'EMPLOYEE_TIME_OFF_SUCCESS';

export const RESET_CHAT = 'RESET_CHAT';
export const RESET_CHAT_SUCCESS = 'RESET_CHAT_SUCCESS';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
